<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class KelurahanSeeder extends Seeder
{
    public function run()
    {
        // Tambahkan data kelurahan ke dalam tabel
        $data = [
            [
                'id_kab' => '71',
                'id_kec' => '010',
                'id_kel' => '001',
                'nama_kel' => 'Pemogan',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '010',
                'id_kel' => '002',
                'nama_kel' => 'Pedungan',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '010',
                'id_kel' => '003',
                'nama_kel' => 'Sesetan',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '010',
                'id_kel' => '004',
                'nama_kel' => 'Serangan',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '010',
                'id_kel' => '005',
                'nama_kel' => 'Sidakarya',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '010',
                'id_kel' => '006',
                'nama_kel' => 'Panjer',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '010',
                'id_kel' => '007',
                'nama_kel' => 'Renon',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '010',
                'id_kel' => '008',
                'nama_kel' => 'Sanur Kauh',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '010',
                'id_kel' => '009',
                'nama_kel' => 'Sanur',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '010',
                'id_kel' => '010',
                'nama_kel' => 'Sanur Kaja',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '020',
                'id_kel' => '001',
                'nama_kel' => 'Dangin Puri Klod',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '020',
                'id_kel' => '002',
                'nama_kel' => 'Sumerta Kelod',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '020',
                'id_kel' => '003',
                'nama_kel' => 'Kesiman',
            ],[
                'id_kab' => '71',
                'id_kec' => '020',
                'id_kel' => '004',
                'nama_kel' => 'Kesiman Petilan',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '020',
                'id_kel' => '005',
                'nama_kel' => 'Kesiman Kertalangu',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '020',
                'id_kel' => '006',
                'nama_kel' => 'Sumerta',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '020',
                'id_kel' => '007',
                'nama_kel' => 'Sumerta Kaja',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '020',
                'id_kel' => '008',
                'nama_kel' => 'Sumerta Kauh',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '030',
                'id_kel' => '001',
                'nama_kel' => 'Padangsambian Klod',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '030',
                'id_kel' => '002',
                'nama_kel' => 'Pemecutan Klod',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '030',
                'id_kel' => '003',
                'nama_kel' => 'Dauh Puri Kauh',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '030',
                'id_kel' => '004',
                'nama_kel' => 'Dauh Puri Klod',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '030',
                'id_kel' => '005',
                'nama_kel' => 'Dauh Puri',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '030',
                'id_kel' => '006',
                'nama_kel' => 'Dauh Puri Kangin',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '030',
                'id_kel' => '007',
                'nama_kel' => 'Pemecutan',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '030',
                'id_kel' => '008',
                'nama_kel' => 'Tegal Harum',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '030',
                'id_kel' => '009',
                'nama_kel' => 'Tegal Kertha',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '030',
                'id_kel' => '010',
                'nama_kel' => 'Padangsambian',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '030',
                'id_kel' => '011',
                'nama_kel' => 'Padangsambian Kaja',
            ],
            [
                'id_kab' => '71',
                'id_kec' => '031',
                'id_kel' => '001',
                'nama_kel' => 'Pemecutan Kaja',
            ],[
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '001',
                'nama_kel' => 'Sumber Klampok',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '002',
                'nama_kel' => 'Pejarakan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '003',
                'nama_kel' => 'Sumberkima',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '004',
                'nama_kel' => 'Pemuteran',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '005',
                'nama_kel' => 'Banyupoh',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '006',
                'nama_kel' => 'Penyabangan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '007',
                'nama_kel' => 'Musi',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '008',
                'nama_kel' => 'Sanggalangit',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '009',
                'nama_kel' => 'Gerokgak',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '010',
                'nama_kel' => 'Patas',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '011',
                'nama_kel' => 'Pengulon',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '012',
                'nama_kel' => 'Tinga Tinga',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '013',
                'nama_kel' => 'Celukan Bawang',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '010',
                'id_kel' => '014',
                'nama_kel' => 'Tukad Sumaga',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '020',
                'id_kel' => '001',
                'nama_kel' => 'Unggahan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '020',
                'id_kel' => '002',
                'nama_kel' => 'Gunungsari',
            ],[
                'id_kab' => '08',
                'id_kec' => '020',
                'id_kel' => '003',
                'nama_kel' => 'Munduk Bestala',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '020',
                'id_kel' => '004',
                'nama_kel' => 'Bestala',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '020',
                'id_kel' => '005',
                'nama_kel' => 'Mayong',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '020',
                'id_kel' => '006',
                'nama_kel' => 'Rangdu',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '020',
                'id_kel' => '007',
                'nama_kel' => 'Ularan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '020',
                'id_kel' => '008',
                'nama_kel' => 'Ringdikit',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '020',
                'id_kel' => '009',
                'nama_kel' => 'Joanyar',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '001',
                'nama_kel' => 'Sepang Kelod',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '002',
                'nama_kel' => 'Tista',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '003',
                'nama_kel' => 'Bongancina',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '004',
                'nama_kel' => 'Pucaksari',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '005',
                'nama_kel' => 'Sepang',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '006',
                'nama_kel' => 'Telaga',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '007',
                'nama_kel' => 'Titab',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '008',
                'nama_kel' => 'Kekeran',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '009',
                'nama_kel' => 'Busungbiu',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '010',
                'nama_kel' => 'Pelapuan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '011',
                'nama_kel' => 'Subuk',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '012',
                'nama_kel' => 'Tinggarsari',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '013',
                'nama_kel' => 'Kedis',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '014',
                'nama_kel' => 'Bengkel',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '030',
                'id_kel' => '015',
                'nama_kel' => 'Umejero',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '001',
                'nama_kel' => 'Banyuatis',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '002',
                'nama_kel' => 'Gesing',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '003',
                'nama_kel' => 'Munduk',
            ], [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '004',
                'nama_kel' => 'Gobleg',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '005',
                'nama_kel' => 'Kayuputih',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '006',
                'nama_kel' => 'Tirtasari',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '007',
                'nama_kel' => 'Banyusri',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '008',
                'nama_kel' => 'Pedawa',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '009',
                'nama_kel' => 'Tigawasa',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '010',
                'nama_kel' => 'Cempaga',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '011',
                'nama_kel' => 'Sidetapa',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '012',
                'nama_kel' => 'Tampekan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '013',
                'nama_kel' => 'Banjar Tegeha',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '014',
                'nama_kel' => 'Banjar',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '015',
                'nama_kel' => 'Dencarik',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '016',
                'nama_kel' => 'Temukus',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '040',
                'id_kel' => '017',
                'nama_kel' => 'Kaliasem',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '001',
                'nama_kel' => 'Pancasari',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '002',
                'nama_kel' => 'Wanagiri',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '003',
                'nama_kel' => 'Ambengan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '004',
                'nama_kel' => 'Gitgit',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '005',
                'nama_kel' => 'Pegayaman',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '006',
                'nama_kel' => 'Silangjana',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '007',
                'nama_kel' => 'Pegadungan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '008',
                'nama_kel' => 'Padangbulia',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '009',
                'nama_kel' => 'Sukasada',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '010',
                'nama_kel' => 'Sambangan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '011',
                'nama_kel' => 'Panji',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '012',
                'nama_kel' => 'Panji Anom',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '013',
                'nama_kel' => 'Tegal Linggah',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '050',
                'id_kel' => '014',
                'nama_kel' => 'Selat',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '001',
                'nama_kel' => 'Kalibukbuk',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '002',
                'nama_kel' => 'Anturan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '003',
                'nama_kel' => 'Tukadmungga',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '004',
                'nama_kel' => 'Pemaron',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '005',
                'nama_kel' => 'Baktiseraga',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '006',
                'nama_kel' => 'Banyuasri',
            ],    [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '007',
                'nama_kel' => 'Banjar Tegal',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '008',
                'nama_kel' => 'Paker Agung',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '009',
                'nama_kel' => 'Beratan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '010',
                'nama_kel' => 'Liligundi',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '011',
                'nama_kel' => 'Kampung Singaraja',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '012',
                'nama_kel' => 'Kendran',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '013',
                'nama_kel' => 'Astina',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '014',
                'nama_kel' => 'Banjar Jawa',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '015',
                'nama_kel' => 'Banjar Bali',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '016',
                'nama_kel' => 'Kampung Kajanan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '017',
                'nama_kel' => 'Kaliuntu',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '018',
                'nama_kel' => 'Kampung Anyar',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '019',
                'nama_kel' => 'Kampung Bugis',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '020',
                'nama_kel' => 'Kampung Baru',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '021',
                'nama_kel' => 'Banyuning',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '022',
                'nama_kel' => 'Penarukan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '023',
                'nama_kel' => 'Jinengdalem',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '024',
                'nama_kel' => 'Penglatan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '025',
                'nama_kel' => 'Petandakan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '026',
                'nama_kel' => 'Sari Mekar',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '027',
                'nama_kel' => 'Nagasepaha',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '028',
                'nama_kel' => 'Alasangker',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '060',
                'id_kel' => '029',
                'nama_kel' => 'Poh Bergong',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '001',
                'nama_kel' => 'Lemukih',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '002',
                'nama_kel' => 'Galungan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '003',
                'nama_kel' => 'Sekumpul',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '004',
                'nama_kel' => 'Bebetin',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '005',
                'nama_kel' => 'Sudaji',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '006',
                'nama_kel' => 'Sawan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '007',
                'nama_kel' => 'Menyali',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '008',
                'nama_kel' => 'Suwug',
            ],[
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '009',
                'nama_kel' => 'Jagaraga',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '010',
                'nama_kel' => 'Sinabun',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '011',
                'nama_kel' => 'Kerobokan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '012',
                'nama_kel' => 'Sangsit',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '013',
                'nama_kel' => 'Bungkulan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '070',
                'id_kel' => '014',
                'nama_kel' => 'Giri Emas',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '001',
                'nama_kel' => 'Tambakan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '002',
                'nama_kel' => 'Pakisan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '003',
                'nama_kel' => 'Bontihing',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '004',
                'nama_kel' => 'Tajun',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '005',
                'nama_kel' => 'Tunjung',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '006',
                'nama_kel' => 'Depeha',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '007',
                'nama_kel' => 'Bulian',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '008',
                'nama_kel' => 'Tamblang',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '009',
                'nama_kel' => 'Bila',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '010',
                'nama_kel' => 'Bengkala',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '011',
                'nama_kel' => 'Kubutambahan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '012',
                'nama_kel' => 'Bukti',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '080',
                'id_kel' => '013',
                'nama_kel' => 'Mengening',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '090',
                'id_kel' => '001',
                'nama_kel' => 'Sembiran',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '090',
                'id_kel' => '002',
                'nama_kel' => 'Pacung',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '090',
                'id_kel' => '003',
                'nama_kel' => 'Julah',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '090',
                'id_kel' => '004',
                'nama_kel' => 'Bondalem',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '090',
                'id_kel' => '005',
                'nama_kel' => 'Madenan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '090',
                'id_kel' => '006',
                'nama_kel' => 'Tejakula',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '090',
                'id_kel' => '007',
                'nama_kel' => 'Les',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '090',
                'id_kel' => '008',
                'nama_kel' => 'Penuktukan',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '090',
                'id_kel' => '009',
                'nama_kel' => 'Sambirenteng',
            ],
            [
                'id_kab' => '08',
                'id_kec' => '090',
                'id_kel' => '010',
                'nama_kel' => 'Tembok',
            ],[
                'id_kab' => '07',
                'id_kec' => '010',
                'id_kel' => '001',
                'nama_kel' => 'Pesaban',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '010',
                'id_kel' => '002',
                'nama_kel' => 'Nongan',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '010',
                'id_kel' => '003',
                'nama_kel' => 'Rendang',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '010',
                'id_kel' => '004',
                'nama_kel' => 'Menanga',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '010',
                'id_kel' => '005',
                'nama_kel' => 'Besakih',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '010',
                'id_kel' => '006',
                'nama_kel' => 'Pempatan',
            ],[
                'id_kab' => '07',
                'id_kec' => '020',
                'id_kel' => '001',
                'nama_kel' => 'Tangkup',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '020',
                'id_kel' => '002',
                'nama_kel' => 'Talibeng',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '020',
                'id_kel' => '003',
                'nama_kel' => 'Telagatawang',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '020',
                'id_kel' => '004',
                'nama_kel' => 'Sidemen',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '020',
                'id_kel' => '005',
                'nama_kel' => 'Sindu Wati',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '020',
                'id_kel' => '006',
                'nama_kel' => 'Sangkan Gunung',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '020',
                'id_kel' => '007',
                'nama_kel' => 'Loka Sari',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '020',
                'id_kel' => '008',
                'nama_kel' => 'Kertha Buana',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '020',
                'id_kel' => '009',
                'nama_kel' => 'Tri Eka Buana',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '020',
                'id_kel' => '010',
                'nama_kel' => 'Wisma Kerta',
            ],[
                'id_kab' => '07',
                'id_kec' => '030',
                'id_kel' => '001',
                'nama_kel' => 'Antiga',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '030',
                'id_kel' => '002',
                'nama_kel' => 'Gegelang',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '030',
                'id_kel' => '003',
                'nama_kel' => 'Padangbai',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '030',
                'id_kel' => '004',
                'nama_kel' => 'Ulakan',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '030',
                'id_kel' => '005',
                'nama_kel' => 'Manggis',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '030',
                'id_kel' => '006',
                'nama_kel' => 'Selumbung',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '030',
                'id_kel' => '007',
                'nama_kel' => 'Ngis',
            ],[
                'id_kab' => '07',
                'id_kec' => '030',
                'id_kel' => '008',
                'nama_kel' => 'Nyuh Tebel',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '030',
                'id_kel' => '009',
                'nama_kel' => 'Tenganan',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '030',
                'id_kel' => '010',
                'nama_kel' => 'Antiga Kelod',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '030',
                'id_kel' => '011',
                'nama_kel' => 'Sengkidu',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '030',
                'id_kel' => '012',
                'nama_kel' => 'Pesedahan',
            ],[
                'id_kab' => '07',
                'id_kec' => '040',
                'id_kel' => '001',
                'nama_kel' => 'Bugbug',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '040',
                'id_kel' => '002',
                'nama_kel' => 'Pertima',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '040',
                'id_kel' => '003',
                'nama_kel' => 'Subagan',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '040',
                'id_kel' => '004',
                'nama_kel' => 'Padang Kerta',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '040',
                'id_kel' => '005',
                'nama_kel' => 'Karangasem',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '040',
                'id_kel' => '006',
                'nama_kel' => 'Tumbu',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '040',
                'id_kel' => '007',
                'nama_kel' => 'Tegallinggah',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '040',
                'id_kel' => '008',
                'nama_kel' => 'Bukit',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '040',
                'id_kel' => '009',
                'nama_kel' => 'Seraya Barat',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '040',
                'id_kel' => '010',
                'nama_kel' => 'Seraya',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '040',
                'id_kel' => '011',
                'nama_kel' => 'Seraya Timur',
            ],[
                'id_kab' => '07',
                'id_kec' => '050',
                'id_kel' => '001',
                'nama_kel' => 'Ababi',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '050',
                'id_kel' => '002',
                'nama_kel' => 'Tiyingtali',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '050',
                'id_kel' => '003',
                'nama_kel' => 'Abang',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '050',
                'id_kel' => '004',
                'nama_kel' => 'Pidpid',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '050',
                'id_kel' => '005',
                'nama_kel' => 'Nawaketi',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '050',
                'id_kel' => '006',
                'nama_kel' => 'Kesimpar',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '050',
                'id_kel' => '007',
                'nama_kel' => 'Tista',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '050',
                'id_kel' => '008',
                'nama_kel' => 'Kerta Mandala',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '050',
                'id_kel' => '009',
                'nama_kel' => 'Culik',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '050',
                'id_kel' => '010',
                'nama_kel' => 'Datah',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '050',
                'id_kel' => '011',
                'nama_kel' => 'Laba Sari',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '050',
                'id_kel' => '012',
                'nama_kel' => 'Purwakerti',
            ], 
            [
                'id_kab' => '07',
                'id_kec' => '060',
                'id_kel' => '001',
                'nama_kel' => 'Sibetan',
            ],[
                'id_kab' => '07',
                'id_kec' => '060',
                'id_kel' => '002',
                'nama_kel' => 'Bebandem',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '060',
                'id_kel' => '003',
                'nama_kel' => 'Bungaya',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '060',
                'id_kel' => '004',
                'nama_kel' => 'Bungaya Kangin',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '060',
                'id_kel' => '005',
                'nama_kel' => 'Budakeling',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '060',
                'id_kel' => '006',
                'nama_kel' => 'Bhuana Giri',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '060',
                'id_kel' => '007',
                'nama_kel' => 'Jungutan',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '060',
                'id_kel' => '008',
                'nama_kel' => 'Macang',
            ],[
                'id_kab' => '07',
                'id_kec' => '070',
                'id_kel' => '001',
                'nama_kel' => 'Muncan',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '070',
                'id_kel' => '002',
                'nama_kel' => 'Pering Sari',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '070',
                'id_kel' => '003',
                'nama_kel' => 'Selat',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '070',
                'id_kel' => '004',
                'nama_kel' => 'Duda',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '070',
                'id_kel' => '005',
                'nama_kel' => 'Duda Timur',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '070',
                'id_kel' => '006',
                'nama_kel' => 'Duda Utara',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '070',
                'id_kel' => '007',
                'nama_kel' => 'Sebudi',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '070',
                'id_kel' => '008',
                'nama_kel' => 'Amerta Bhuana',
            ],[
                'id_kab' => '07',
                'id_kec' => '080',
                'id_kel' => '001',
                'nama_kel' => 'Ban',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '080',
                'id_kel' => '002',
                'nama_kel' => 'Dukuh',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '080',
                'id_kel' => '003',
                'nama_kel' => 'Tulamben',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '080',
                'id_kel' => '004',
                'nama_kel' => 'Kudu',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '080',
                'id_kel' => '005',
                'nama_kel' => 'Baturinggit',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '080',
                'id_kel' => '006',
                'nama_kel' => 'Sukadana',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '080',
                'id_kel' => '007',
                'nama_kel' => 'Tianyar',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '080',
                'id_kel' => '008',
                'nama_kel' => 'Tianyar Tengah',
            ],
            [
                'id_kab' => '07',
                'id_kec' => '080',
                'id_kel' => '009',
                'nama_kel' => 'Tianyar Barat',
            ],
        
            // BANGLI
            [
                'id_kab' => '06',
                'id_kec' => '010',
                'id_kel' => '001',
                'nama_kel' => 'Apuan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '010',
                'id_kel' => '002',
                'nama_kel' => 'Abuan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '010',
                'id_kel' => '003',
                'nama_kel' => 'Demulih',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '010',
                'id_kel' => '004',
                'nama_kel' => 'Susut',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '010',
                'id_kel' => '005',
                'nama_kel' => 'Sulahan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '010',
                'id_kel' => '006',
                'nama_kel' => 'Tiga',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '010',
                'id_kel' => '007',
                'nama_kel' => 'Penglumbaran',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '010',
                'id_kel' => '008',
                'nama_kel' => 'Selat',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '010',
                'id_kel' => '009',
                'nama_kel' => 'Pengiangan',
            ],[
                'id_kab' => '06',
                'id_kec' => '020',
                'id_kel' => '001',
                'nama_kel' => 'Bunutin',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '020',
                'id_kel' => '002',
                'nama_kel' => 'Taman Bali',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '020',
                'id_kel' => '003',
                'nama_kel' => 'Bebalang',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '020',
                'id_kel' => '004',
                'nama_kel' => 'Kawan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '020',
                'id_kel' => '005',
                'nama_kel' => 'Cempaga',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '020',
                'id_kel' => '006',
                'nama_kel' => 'Kubu',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '020',
                'id_kel' => '007',
                'nama_kel' => 'Kayubihi',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '020',
                'id_kel' => '008',
                'nama_kel' => 'Pengotan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '020',
                'id_kel' => '009',
                'nama_kel' => 'Landih',
            ], [
                'id_kab' => '06',
                'id_kec' => '030',
                'id_kel' => '001',
                'nama_kel' => 'Jehem',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '030',
                'id_kel' => '002',
                'nama_kel' => 'Tembuku',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '030',
                'id_kel' => '003',
                'nama_kel' => 'Yangapi',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '030',
                'id_kel' => '004',
                'nama_kel' => 'Undisan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '030',
                'id_kel' => '005',
                'nama_kel' => 'Bangbang',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '030',
                'id_kel' => '006',
                'nama_kel' => 'Peninjoan',
            ],[
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '001',
                'nama_kel' => 'Mengani',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '002',
                'nama_kel' => 'Binyan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '003',
                'nama_kel' => 'Ulian',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '004',
                'nama_kel' => 'Bunutin',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '005',
                'nama_kel' => 'Langgahan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '006',
                'nama_kel' => 'Lembean',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '007',
                'nama_kel' => 'Bayungcerik',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '008',
                'nama_kel' => 'Mangguh',
            ],[
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '009',
                'nama_kel' => 'Belancan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '010',
                'nama_kel' => 'Katung',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '011',
                'nama_kel' => 'Banua',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '012',
                'nama_kel' => 'Abuan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '013',
                'nama_kel' => 'Bonyoh',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '014',
                'nama_kel' => 'Sekaan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '015',
                'nama_kel' => 'Bayung Gede',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '016',
                'nama_kel' => 'Sekardadi',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '017',
                'nama_kel' => 'Kedisan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '018',
                'nama_kel' => 'Buahan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '019',
                'nama_kel' => 'Suter',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '020',
                'nama_kel' => 'Abang Batu Dinding',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '021',
                'nama_kel' => 'Abang Songan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '022',
                'nama_kel' => 'Terunyan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '023',
                'nama_kel' => 'Songan B',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '024',
                'nama_kel' => 'Songan A',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '025',
                'nama_kel' => 'Batur Selatan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '026',
                'nama_kel' => 'Batur Tengah',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '027',
                'nama_kel' => 'Batur Utara',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '028',
                'nama_kel' => 'Kintamani',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '029',
                'nama_kel' => 'Serahi',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '030',
                'nama_kel' => 'Manikliyu',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '031',
                'nama_kel' => 'Awan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '032',
                'nama_kel' => 'Belantih',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '033',
                'nama_kel' => 'Gunungbau',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '034',
                'nama_kel' => 'Belanga',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '035',
                'nama_kel' => 'Batukaang',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '036',
                'nama_kel' => 'Catur',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '037',
                'nama_kel' => 'Pengejaran',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '038',
                'nama_kel' => 'Satra',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '039',
                'nama_kel' => 'Selulung',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '040',
                'nama_kel' => 'Dausa',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '041',
                'nama_kel' => 'Daup',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '042',
                'nama_kel' => 'Bantang',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '043',
                'nama_kel' => 'Kutuh',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '044',
                'nama_kel' => 'Sukawana',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '045',
                'nama_kel' => 'Subaya',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '046',
                'nama_kel' => 'Siyakin',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '047',
                'nama_kel' => 'Pinggan',
            ],
            [
                'id_kab' => '06',
                'id_kec' => '040',
                'id_kel' => '048',
                'nama_kel' => 'Belandingan',
            ],
            
    
        ];

        // Insert data ke dalam tabel
        $this->db->table('kelurahan')->insertBatch($data);
    }
}
