<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class KelurahanSeeder extends Seeder
{
    public function run()
    {
        // Tambahkan data kelurahan ke dalam tabel
        $data = [
            //Jembrana
            [
                'id_kab' => '01',
                'id_kec' => '010',
                'id_kel' => '001',
                'nama_kel' => 'Gilimanuk',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '010',
                'id_kel' => '002',
                'nama_kel' => 'Melaya',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '010',
                'id_kel' => '003',
                'nama_kel' => 'Candikusuma',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '010',
                'id_kel' => '004',
                'nama_kel' => 'Tuwed',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '010',
                'id_kel' => '005',
                'nama_kel' => 'Tukadaya',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '010',
                'id_kel' => '006',
                'nama_kel' => 'Manistutu',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '010',
                'id_kel' => '007',
                'nama_kel' => 'Warnasari',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '010',
                'id_kel' => '008',
                'nama_kel' => 'Nusa Sari',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '010',
                'id_kel' => '009',
                'nama_kel' => 'Ekasari',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '010',
                'id_kel' => '010',
                'nama_kel' => 'Blimbingsari',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '020',
                'id_kel' => '001',
                'nama_kel' => 'Cupel',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '020',
                'id_kel' => '002',
                'nama_kel' => 'Tegal Badeng Barat',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '020',
                'id_kel' => '003',
                'nama_kel' => 'Tegal Badeng Timur',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '020',
                'id_kel' => '004',
                'nama_kel' => 'Pengambengan',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '020',
                'id_kel' => '012',
                'nama_kel' => 'Loloan Barat',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '020',
                'id_kel' => '013',
                'nama_kel' => 'Lelateng',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '020',
                'id_kel' => '014',
                'nama_kel' => 'Banjar Tengah',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '020',
                'id_kel' => '015',
                'nama_kel' => 'Baluk',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '020',
                'id_kel' => '016',
                'nama_kel' => 'Banyubiru',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '020',
                'id_kel' => '017',
                'nama_kel' => 'Kaliakah',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '020',
                'id_kel' => '018',
                'nama_kel' => 'Berangbang',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '020',
                'id_kel' => '019',
                'nama_kel' => 'Baler Bale Agung',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '021',
                'id_kel' => '001',
                'nama_kel' => 'Perancak',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '021',
                'id_kel' => '002',
                'nama_kel' => 'Air Kuning',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '021',
                'id_kel' => '003',
                'nama_kel' => 'Yeh Kuning',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '021',
                'id_kel' => '004',
                'nama_kel' => 'Budeng',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '021',
                'id_kel' => '005',
                'nama_kel' => 'Sangkaragung',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '021',
                'id_kel' => '006',
                'nama_kel' => 'Dauhwaru',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '021',
                'id_kel' => '007',
                'nama_kel' => 'Loloan Timur',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '021',
                'id_kel' => '008',
                'nama_kel' => 'Pendem',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '021',
                'id_kel' => '009',
                'nama_kel' => 'Batuagung',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '021',
                'id_kel' => '010',
                'nama_kel' => 'Dangin Tukadaya',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '030',
                'id_kel' => '001',
                'nama_kel' => 'Mendoyo Dauh Tukad',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '030',
                'id_kel' => '002',
                'nama_kel' => 'Mendoyo Dangin Tukad',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '030',
                'id_kel' => '003',
                'nama_kel' => 'Pohsanten',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '030',
                'id_kel' => '004',
                'nama_kel' => 'Pergung',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '030',
                'id_kel' => '005',
                'nama_kel' => 'Delod Berawah',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '030',
                'id_kel' => '006',
                'nama_kel' => 'Tegal Cangkring',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '030',
                'id_kel' => '007',
                'nama_kel' => 'Penyaringan',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '030',
                'id_kel' => '008',
                'nama_kel' => 'Yeh Embang Kauh',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '030',
                'id_kel' => '009',
                'nama_kel' => 'Yeh Embang',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '030',
                'id_kel' => '010',
                'nama_kel' => 'Yeh Embang Kangin',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '030',
                'id_kel' => '011',
                'nama_kel' => 'Yeh Sumbul',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '040',
                'id_kel' => '001',
                'nama_kel' => 'Medewi',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '040',
                'id_kel' => '002',
                'nama_kel' => 'Pulukan',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '040',
                'id_kel' => '003',
                'nama_kel' => 'Pekutatan',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '040',
                'id_kel' => '004',
                'nama_kel' => 'Pangyangan',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '040',
                'id_kel' => '005',
                'nama_kel' => 'Gumbrih',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '040',
                'id_kel' => '006',
                'nama_kel' => 'Pengeragoan',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '040',
                'id_kel' => '007',
                'nama_kel' => 'Asahduren',
            ],
            [
                'id_kab' => '01',
                'id_kec' => '040',
                'id_kel' => '008',
                'nama_kel' => 'Manggissari',
            ],

            // Tabanan
            [
                'id_kab' => '02',
                'id_kec' => '010',
                'id_kel' => '002',
                'nama_kel' => 'Antap',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '010',
                'id_kel' => '004',
                'nama_kel' => 'Bajera',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '010',
                'id_kel' => '005',
                'nama_kel' => 'Berembeng',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '010',
                'id_kel' => '006',
                'nama_kel' => 'Serampingan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '010',
                'id_kel' => '014',
                'nama_kel' => 'Selemadeg',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '010',
                'id_kel' => '015',
                'nama_kel' => 'Pupuan Sawah',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '010',
                'id_kel' => '018',
                'nama_kel' => 'Wanagiri',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '010',
                'id_kel' => '024',
                'nama_kel' => 'Wanagiri Kauh',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '010',
                'id_kel' => '025',
                'nama_kel' => 'Manikyang',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '010',
                'id_kel' => '026',
                'nama_kel' => 'Bajera Utara',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '011',
                'id_kel' => '001',
                'nama_kel' => 'Tegal Mengkeb',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '011',
                'id_kel' => '002',
                'nama_kel' => 'Beraban',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '011',
                'id_kel' => '003',
                'nama_kel' => 'Tangguntiti',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '011',
                'id_kel' => '004',
                'nama_kel' => 'Mambang',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '011',
                'id_kel' => '005',
                'nama_kel' => 'Bantas',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '011',
                'id_kel' => '006',
                'nama_kel' => 'Megati',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '011',
                'id_kel' => '007',
                'nama_kel' => 'Gadungan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '011',
                'id_kel' => '008',
                'nama_kel' => 'Gunung Salak',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '011',
                'id_kel' => '009',
                'nama_kel' => 'Dalang',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '011',
                'id_kel' => '010',
                'nama_kel' => 'Gadung Sari',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '012',
                'id_kel' => '001',
                'nama_kel' => 'Lalang Linggah',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '012',
                'id_kel' => '002',
                'nama_kel' => 'Antosari',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '012',
                'id_kel' => '003',
                'nama_kel' => 'Tiying Gading',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '012',
                'id_kel' => '004',
                'nama_kel' => 'Lumbung',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '012',
                'id_kel' => '005',
                'nama_kel' => 'Lumbung Kauh',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '012',
                'id_kel' => '006',
                'nama_kel' => 'Mundeh',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '012',
                'id_kel' => '007',
                'nama_kel' => 'Mundeh Kangin',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '012',
                'id_kel' => '008',
                'nama_kel' => 'Angkah',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '012',
                'id_kel' => '009',
                'nama_kel' => 'Mundeh Kauh',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '012',
                'id_kel' => '010',
                'nama_kel' => 'Selabih',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '012',
                'id_kel' => '011',
                'nama_kel' => 'Bengkel Sari',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '001',
                'nama_kel' => 'Tibubiyu',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '002',
                'nama_kel' => 'Kelating',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '003',
                'nama_kel' => 'Penarukan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '004',
                'nama_kel' => 'Belumbang',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '005',
                'nama_kel' => 'Tista',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '006',
                'nama_kel' => 'Kerambitan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '007',
                'nama_kel' => 'Pangkung Karung',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '008',
                'nama_kel' => 'Kukuh',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '009',
                'nama_kel' => 'Baturiti',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '010',
                'nama_kel' => 'Meliling',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '011',
                'nama_kel' => 'Sembung Gede',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '012',
                'nama_kel' => 'Samsam',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '013',
                'nama_kel' => 'Batuaji',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '014',
                'nama_kel' => 'Kesiut',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '020',
                'id_kel' => '015',
                'nama_kel' => 'Timpag',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '030',
                'id_kel' => '001',
                'nama_kel' => 'Sudimara',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '030',
                'id_kel' => '002',
                'nama_kel' => 'Bongan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '030',
                'id_kel' => '003',
                'nama_kel' => 'Gubug',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '030',
                'id_kel' => '004',
                'nama_kel' => 'Dauh Peken',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '030',
                'id_kel' => '005',
                'nama_kel' => 'Delod Peken',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '030',
                'id_kel' => '006',
                'nama_kel' => 'Dajan Peken',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '030',
                'id_kel' => '007',
                'nama_kel' => 'Subamia',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '030',
                'id_kel' => '008',
                'nama_kel' => 'Denbantas',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '030',
                'id_kel' => '009',
                'nama_kel' => 'Buahan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '030',
                'id_kel' => '010',
                'nama_kel' => 'Tunjuk',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '030',
                'id_kel' => '011',
                'nama_kel' => 'Wanasari',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '030',
                'id_kel' => '012',
                'nama_kel' => 'Sesandan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '001',
                'nama_kel' => 'Pangkung Tibah',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '002',
                'nama_kel' => 'Belalang',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '003',
                'nama_kel' => 'Beraban',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '004',
                'nama_kel' => 'Buwit',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '005',
                'nama_kel' => 'Cepaka',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '006',
                'nama_kel' => 'Kaba-kaba',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '007',
                'nama_kel' => 'Pandak Gede',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '008',
                'nama_kel' => 'Bengkel',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '009',
                'nama_kel' => 'Pejaten',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '010',
                'nama_kel' => 'Nyitdah',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '011',
                'nama_kel' => 'Pandak Bandung',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '012',
                'nama_kel' => 'Nyambu',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '013',
                'nama_kel' => 'Kediri',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '014',
                'nama_kel' => 'Abian Tuwung',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '040',
                'id_kel' => '015',
                'nama_kel' => 'Banjar Anyar',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '001',
                'nama_kel' => 'Tegaljadi',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '002',
                'nama_kel' => 'Kukuh',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '003',
                'nama_kel' => 'Beringkit Belayu',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '004',
                'nama_kel' => 'Peken Belayu',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '005',
                'nama_kel' => 'Batannyuh',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '006',
                'nama_kel' => 'Kuwum',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '007',
                'nama_kel' => 'Caubelayu',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '008',
                'nama_kel' => 'Selanbawak',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '009',
                'nama_kel' => 'Marga',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '010',
                'nama_kel' => 'Petiga',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '011',
                'nama_kel' => 'Tua',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '012',
                'nama_kel' => 'Payangan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '013',
                'nama_kel' => 'Dauh Puri',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '014',
                'nama_kel' => 'Dajan Puri',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '015',
                'nama_kel' => 'Geluntung',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '050',
                'id_kel' => '016',
                'nama_kel' => 'Baru',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '060',
                'id_kel' => '001',
                'nama_kel' => 'Perean',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '060',
                'id_kel' => '002',
                'nama_kel' => 'Perean Tengah',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '060',
                'id_kel' => '003',
                'nama_kel' => 'Perean Kangin',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '060',
                'id_kel' => '004',
                'nama_kel' => 'Luwus',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '060',
                'id_kel' => '005',
                'nama_kel' => 'Mekarsari',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '060',
                'id_kel' => '006',
                'nama_kel' => 'Apuan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '060',
                'id_kel' => '007',
                'nama_kel' => 'Angseri',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '060',
                'id_kel' => '008',
                'nama_kel' => 'Bangli',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '060',
                'id_kel' => '009',
                'nama_kel' => 'Baturiti',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '060',
                'id_kel' => '010',
                'nama_kel' => 'Batunya',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '060',
                'id_kel' => '011',
                'nama_kel' => 'Antapan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '060',
                'id_kel' => '012',
                'nama_kel' => 'Candikuning',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '001',
                'nama_kel' => 'Rejasa',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '002',
                'nama_kel' => 'Jegu',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '003',
                'nama_kel' => 'Riang Gede',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '004',
                'nama_kel' => 'Buruan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '005',
                'nama_kel' => 'Tajen',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '006',
                'nama_kel' => 'Pitra',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '007',
                'nama_kel' => 'Penatahan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '008',
                'nama_kel' => 'Tengkudak',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '009',
                'nama_kel' => 'Mengeste',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '010',
                'nama_kel' => 'Penebel',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '011',
                'nama_kel' => 'Biaung',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '012',
                'nama_kel' => 'Babahan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '013',
                'nama_kel' => 'Senganan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '014',
                'nama_kel' => 'Jatiluwih',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '015',
                'nama_kel' => 'Wongaya Gede',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '016',
                'nama_kel' => 'Pesagi',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '017',
                'nama_kel' => 'Tegalinggah',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '070',
                'id_kel' => '018',
                'nama_kel' => 'Sangketan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '001',
                'nama_kel' => 'Belatungan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '002',
                'nama_kel' => 'Kebon Padangan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '003',
                'nama_kel' => 'Belimbing',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '004',
                'nama_kel' => 'Sanda',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '005',
                'nama_kel' => 'Batungsel',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '006',
                'nama_kel' => 'Pujungan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '007',
                'nama_kel' => 'Pajahan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '008',
                'nama_kel' => 'Munduk Temu',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '009',
                'nama_kel' => 'Pupuan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '010',
                'nama_kel' => 'Bantiran',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '011',
                'nama_kel' => 'Padangan',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '012',
                'nama_kel' => 'Jelijih Punggang',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '013',
                'nama_kel' => 'Karya Sari',
            ],
            [
                'id_kab' => '02',
                'id_kec' => '080',
                'id_kel' => '014',
                'nama_kel' => 'Sai',
            ],

            //Badung
            [
                'id_kab' => '03',
                'id_kec' => '010',
                'id_kel' => '001',
                'nama_kel' => 'Pecatu',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '010',
                'id_kel' => '002',
                'nama_kel' => 'Ungasan',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '010',
                'id_kel' => '003',
                'nama_kel' => 'Kutuh',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '010',
                'id_kel' => '004',
                'nama_kel' => 'Benoa',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '010',
                'id_kel' => '005',
                'nama_kel' => 'Tanjung Benoa',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '010',
                'id_kel' => '006',
                'nama_kel' => 'Jimbaran',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '020',
                'id_kel' => '001',
                'nama_kel' => 'Kedongan',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '020',
                'id_kel' => '002',
                'nama_kel' => 'Tuban',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '020',
                'id_kel' => '003',
                'nama_kel' => 'Kuta',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '020',
                'id_kel' => '004',
                'nama_kel' => 'Legian',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '020',
                'id_kel' => '005',
                'nama_kel' => 'Seminyak',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '030',
                'id_kel' => '001',
                'nama_kel' => 'Kerobokan Kelod',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '030',
                'id_kel' => '002',
                'nama_kel' => 'Kerobokan',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '030',
                'id_kel' => '003',
                'nama_kel' => 'Kerobokan Kaja',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '030',
                'id_kel' => '004',
                'nama_kel' => 'Tibubeneng',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '030',
                'id_kel' => '005',
                'nama_kel' => 'Canggu',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '030',
                'id_kel' => '006',
                'nama_kel' => 'Dalung',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '001',
                'nama_kel' => 'Cemagi',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '002',
                'nama_kel' => 'Munggu',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '003',
                'nama_kel' => 'Pererenan',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '004',
                'nama_kel' => 'Tumbak Bayuh',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '005',
                'nama_kel' => 'Buduk',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '006',
                'nama_kel' => 'Abianbase',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '007',
                'nama_kel' => 'Sempidi',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '008',
                'nama_kel' => 'Sading',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '009',
                'nama_kel' => 'Lukluk',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '010',
                'nama_kel' => 'Kapal',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '011',
                'nama_kel' => 'Kekeran',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '012',
                'nama_kel' => 'Mengwitani',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '013',
                'nama_kel' => 'Mengwi',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '014',
                'nama_kel' => 'Gulingan',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '015',
                'nama_kel' => 'Penarungan',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '016',
                'nama_kel' => 'Baha',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '017',
                'nama_kel' => 'Werdi Bhuwana',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '018',
                'nama_kel' => 'Sobangan',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '019',
                'nama_kel' => 'Sembung',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '040',
                'id_kel' => '020',
                'nama_kel' => 'Kuwum',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '001',
                'nama_kel' => 'Darmasaba',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '002',
                'nama_kel' => 'Sibang Gede',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '003',
                'nama_kel' => 'Jagapati',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '004',
                'nama_kel' => 'Angantaka',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '005',
                'nama_kel' => 'Sedang',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '006',
                'nama_kel' => 'Sibang Kaja',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '007',
                'nama_kel' => 'Mekar Bhuana',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '008',
                'nama_kel' => 'Mambal',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '009',
                'nama_kel' => 'Abiansemal',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '010',
                'nama_kel' => 'Dauh Yeh Cani',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '011',
                'nama_kel' => 'Ayunan',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '012',
                'nama_kel' => 'Blahkiuh',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '013',
                'nama_kel' => 'Punggul',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '014',
                'nama_kel' => 'Bongkasa',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '015',
                'nama_kel' => 'Taman',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '016',
                'nama_kel' => 'Selat',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '017',
                'nama_kel' => 'Sangeh',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '050',
                'id_kel' => '018',
                'nama_kel' => 'Bongkasa Pertiwi',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '060',
                'id_kel' => '001',
                'nama_kel' => 'Carangsari',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '060',
                'id_kel' => '002',
                'nama_kel' => 'Getasan',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '060',
                'id_kel' => '003',
                'nama_kel' => 'Pangsan',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '060',
                'id_kel' => '004',
                'nama_kel' => 'Petang',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '060',
                'id_kel' => '005',
                'nama_kel' => 'Sulangai',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '060',
                'id_kel' => '006',
                'nama_kel' => 'Pelaga',
            ],
            [
                'id_kab' => '03',
                'id_kec' => '060',
                'id_kel' => '007',
                'nama_kel' => 'Belok/Sidan',
            ],

            //Gianyar
            [
                'id_kab' => '04',
                'id_kec' => '010',
                'id_kel' => '001',
                'nama_kel' => 'Batubulan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '010',
                'id_kel' => '002',
                'nama_kel' => 'Batubulan Kangin',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '010',
                'id_kel' => '003',
                'nama_kel' => 'Ketewel',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '010',
                'id_kel' => '004',
                'nama_kel' => 'Guwang',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '010',
                'id_kel' => '005',
                'nama_kel' => 'Sukawati',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '010',
                'id_kel' => '006',
                'nama_kel' => 'Celuk',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '010',
                'id_kel' => '007',
                'nama_kel' => 'Singapadu',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '010',
                'id_kel' => '008',
                'nama_kel' => 'Singapadu Tengah',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '010',
                'id_kel' => '009',
                'nama_kel' => 'Singapadu Kaler',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '010',
                'id_kel' => '010',
                'nama_kel' => 'Batuan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '010',
                'id_kel' => '011',
                'nama_kel' => 'Batuan Kaler',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '010',
                'id_kel' => '012',
                'nama_kel' => 'Kemenuh',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '020',
                'id_kel' => '001',
                'nama_kel' => 'Saba',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '020',
                'id_kel' => '002',
                'nama_kel' => 'Pering',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '020',
                'id_kel' => '003',
                'nama_kel' => 'Keramas',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '020',
                'id_kel' => '004',
                'nama_kel' => 'Medahan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '020',
                'id_kel' => '005',
                'nama_kel' => 'Bona',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '020',
                'id_kel' => '006',
                'nama_kel' => 'Belega',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '020',
                'id_kel' => '007',
                'nama_kel' => 'Blahbatuh',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '020',
                'id_kel' => '008',
                'nama_kel' => 'Buruan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '020',
                'id_kel' => '009',
                'nama_kel' => 'Bedulu',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '001',
                'nama_kel' => 'Lebih',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '002',
                'nama_kel' => 'Tulikup',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '003',
                'nama_kel' => 'Temesi',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '004',
                'nama_kel' => 'Sidan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '005',
                'nama_kel' => 'Samplangan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '006',
                'nama_kel' => 'Serongga',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '007',
                'nama_kel' => 'Abianbase',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '008',
                'nama_kel' => 'Gianyar',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '009',
                'nama_kel' => 'Beng',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '010',
                'nama_kel' => 'Bitera',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '011',
                'nama_kel' => 'Bakbakan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '012',
                'nama_kel' => 'Siangan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '013',
                'nama_kel' => 'Suwat',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '014',
                'nama_kel' => 'Petak',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '015',
                'nama_kel' => 'Petak Kaja',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '016',
                'nama_kel' => 'Sumita',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '030',
                'id_kel' => '017',
                'nama_kel' => 'Tegal Tugu',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '040',
                'id_kel' => '001',
                'nama_kel' => 'Pejeng Kawan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '040',
                'id_kel' => '002',
                'nama_kel' => 'Pejeng',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '040',
                'id_kel' => '003',
                'nama_kel' => 'Pejeng Kelod',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '040',
                'id_kel' => '004',
                'nama_kel' => 'Pejeng Kangin',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '040',
                'id_kel' => '005',
                'nama_kel' => 'Pejeng Kaja',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '040',
                'id_kel' => '006',
                'nama_kel' => 'Sanding',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '040',
                'id_kel' => '007',
                'nama_kel' => 'Tampaksiring',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '040',
                'id_kel' => '008',
                'nama_kel' => 'Manukaya',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '050',
                'id_kel' => '001',
                'nama_kel' => 'Singakerta',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '050',
                'id_kel' => '002',
                'nama_kel' => 'Lodtunduh',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '050',
                'id_kel' => '003',
                'nama_kel' => 'Mas',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '050',
                'id_kel' => '004',
                'nama_kel' => 'Peliatan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '050',
                'id_kel' => '005',
                'nama_kel' => 'Petulu',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '050',
                'id_kel' => '006',
                'nama_kel' => 'Ubud',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '050',
                'id_kel' => '007',
                'nama_kel' => 'Sayan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '050',
                'id_kel' => '008',
                'nama_kel' => 'Kedewatan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '060',
                'id_kel' => '001',
                'nama_kel' => 'Keliki',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '060',
                'id_kel' => '002',
                'nama_kel' => 'Tegallalang',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '060',
                'id_kel' => '003',
                'nama_kel' => 'Kenderan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '060',
                'id_kel' => '004',
                'nama_kel' => 'Kedisan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '060',
                'id_kel' => '005',
                'nama_kel' => 'Pupuan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '060',
                'id_kel' => '006',
                'nama_kel' => 'Sebatu',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '060',
                'id_kel' => '007',
                'nama_kel' => 'Taro',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '070',
                'id_kel' => '001',
                'nama_kel' => 'Melinggih Kelod',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '070',
                'id_kel' => '002',
                'nama_kel' => 'Melinggih',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '070',
                'id_kel' => '003',
                'nama_kel' => 'Kelusa',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '070',
                'id_kel' => '004',
                'nama_kel' => 'Beresela',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '070',
                'id_kel' => '005',
                'nama_kel' => 'Bukian',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '070',
                'id_kel' => '006',
                'nama_kel' => 'Puhu',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '070',
                'id_kel' => '007',
                'nama_kel' => 'Buahan',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '070',
                'id_kel' => '008',
                'nama_kel' => 'Buahan Kerja',
            ],
            [
                'id_kab' => '04',
                'id_kec' => '070',
                'id_kel' => '009',
                'nama_kel' => 'Kerta',
            ],

            //Klungkung
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '001',
                'nama_kel' => 'Sakti',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '002',
                'nama_kel' => 'Bunga Mekar',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '003',
                'nama_kel' => 'Batumadeg',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '004',
                'nama_kel' => 'Klumpu',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '005',
                'nama_kel' => 'Batukandik',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '006',
                'nama_kel' => 'Sekartaji',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '007',
                'nama_kel' => 'Tanglad',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '008',
                'nama_kel' => 'Pejukutan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '009',
                'nama_kel' => 'Suana',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '010',
                'nama_kel' => 'Batununggul',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '011',
                'nama_kel' => 'Kutampi',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '012',
                'nama_kel' => 'Kutampi Kaler',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '013',
                'nama_kel' => 'Ped',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '014',
                'nama_kel' => 'Kampung Toyapakeh',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '015',
                'nama_kel' => 'Lembongan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '010',
                'id_kel' => '016',
                'nama_kel' => 'Jungutbatu',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '001',
                'nama_kel' => 'Negari',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '002',
                'nama_kel' => 'Takmung',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '003',
                'nama_kel' => 'Banjarangkan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '004',
                'nama_kel' => 'Tusan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '005',
                'nama_kel' => 'Bakas',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '006',
                'nama_kel' => 'Getakan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '007',
                'nama_kel' => 'Tihingan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '008',
                'nama_kel' => 'Aan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '009',
                'nama_kel' => 'Nyalian',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '010',
                'nama_kel' => 'Bungbungan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '011',
                'nama_kel' => 'Timuhun',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '012',
                'nama_kel' => 'Nyanglan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '020',
                'id_kel' => '013',
                'nama_kel' => 'Tohpati',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '001',
                'nama_kel' => 'Satra',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '002',
                'nama_kel' => 'Tojan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '003',
                'nama_kel' => 'Gelgel',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '004',
                'nama_kel' => 'Kampung Gelgel',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '005',
                'nama_kel' => 'Jumpai',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '006',
                'nama_kel' => 'Tangkas',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '007',
                'nama_kel' => 'Kamasan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '008',
                'nama_kel' => 'Semarapura Kelod',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '009',
                'nama_kel' => 'Semarapura Kelod Kangin',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '010',
                'nama_kel' => 'Semarapura Kangin',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '011',
                'nama_kel' => 'Semarapura Tengah',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '012',
                'nama_kel' => 'Semarapura Kauh',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '013',
                'nama_kel' => 'Semarapura Kaja',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '014',
                'nama_kel' => 'Akah',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '015',
                'nama_kel' => 'Manduang',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '016',
                'nama_kel' => 'Selat',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '017',
                'nama_kel' => 'Tegak',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '030',
                'id_kel' => '018',
                'nama_kel' => 'Selisihan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '040',
                'id_kel' => '001',
                'nama_kel' => 'Kusamba',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '040',
                'id_kel' => '002',
                'nama_kel' => 'Kampung Kusamba',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '040',
                'id_kel' => '003',
                'nama_kel' => 'Pesinggahan',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '040',
                'id_kel' => '004',
                'nama_kel' => 'Dawan Klod',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '040',
                'id_kel' => '005',
                'nama_kel' => 'Gunaksa',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '040',
                'id_kel' => '006',
                'nama_kel' => 'Sampalan Klod',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '040',
                'id_kel' => '007',
                'nama_kel' => 'Sampalan Tengah',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '040',
                'id_kel' => '008',
                'nama_kel' => 'Sulang',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '040',
                'id_kel' => '009',
                'nama_kel' => 'Paksebali',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '040',
                'id_kel' => '010',
                'nama_kel' => 'Dawan Kaler',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '040',
                'id_kel' => '011',
                'nama_kel' => 'Pikat',
            ],
            [
                'id_kab' => '05',
                'id_kec' => '040',
                'id_kel' => '012',
                'nama_kel' => 'Besan',
            ],

        ];

        // Insert data ke dalam tabel
        $this->db->table('kelurahan')->insertBatch($data);
    }
}
