<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class RumahTanggaSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'kode_ruta'       => '444A001',
                'no_segmen'      => 1,
                'no_bg_fisik'    => 1,
                'no_bg_sensus'   => 1,
                'no_urut_rt'     => 1,
                'nama_krt'       => 'KH Ahmad Syamsuri',
                'alamat'         => 'Gentan, Sidorejo, Lendah, Kulon Progo',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 2,
                'no_urut_rt_egb' => 1,
                'long'           => 107.6098,
                'lat'            => -6.9175,
                'catatan'        => 'Catatan Rumah Tangga 1',
            ],
            [
                'kode_ruta'       => '444A002',
                'no_segmen'      => 1,
                'no_bg_fisik'    => 2,
                'no_bg_sensus'   => 2,
                'no_urut_rt'     => 2,
                'nama_krt'       => 'Gus Hilmy Yahya',
                'alamat'         => 'Krapayak, Bantul, DIY',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 2,
                'no_urut_rt_egb' => 2,
                'long'           => 108.1234,
                'lat'            => -7.4321,
                'catatan'        => 'Catatan Rumah Tangga 2',
            ],
            [
                'kode_ruta'       => '444A003',
                'no_segmen'      => 1,
                'no_bg_fisik'    => 3,
                'no_bg_sensus'   => 3,
                'no_urut_rt'     => 3,
                'nama_krt'       => 'Putri Sari',
                'alamat'         => 'Jalan Jenderal Sudirman, Sleman, DIY',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 1,
                'no_urut_rt_egb' => 3,
                'long'           => 110.4090,
                'lat'            => -7.7926,
                'catatan'        => 'Catatan Rumah Tangga 3',
            ],
            [
                'kode_ruta'       => '444A004',
                'no_segmen'      => 1,
                'no_bg_fisik'    => 4,
                'no_bg_sensus'   => 4,
                'no_urut_rt'     => 4,
                'nama_krt'       => 'Agus Setiawan',
                'alamat'         => 'Mangunan, Dlingo, Bantul',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 3,
                'no_urut_rt_egb' => 4,
                'long'           => 110.3060,
                'lat'            => -7.9103,
                'catatan'        => 'Catatan Rumah Tangga 4',
            ],
            [
                'kode_ruta'       => '444A005',
                'no_segmen'      => 1,
                'no_bg_fisik'    => 5,
                'no_bg_sensus'   => 5,
                'no_urut_rt'     => 5,
                'nama_krt'       => 'Siti Nurhayati',
                'alamat'         => 'Tirtomartani, Kalasan, Sleman',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 2,
                'no_urut_rt_egb' => 5,
                'long'           => 110.4223,
                'lat'            => -7.7987,
                'catatan'        => 'Catatan Rumah Tangga 5',
            ],
            [
                'kode_ruta'       => '444A006',
                'no_segmen'      => 2,
                'no_bg_fisik'    => 6,
                'no_bg_sensus'   => 6,
                'no_urut_rt'     => 6,
                'nama_krt'       => 'Andi Susanto',
                'alamat'         => 'Pandak, Bantul, DIY',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 1,
                'no_urut_rt_egb' => 6,
                'long'           => 110.3660,
                'lat'            => -7.8692,
                'catatan'        => 'Catatan Rumah Tangga 6',
            ],
            [
                'kode_ruta'       => '444A007',
                'no_segmen'      => 2,
                'no_bg_fisik'    => 7,
                'no_bg_sensus'   => 7,
                'no_urut_rt'     => 7,
                'nama_krt'       => 'Dewi Lestari',
                'alamat'         => 'Godean, Sleman, DIY',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 3,
                'no_urut_rt_egb' => 7,
                'long'           => 110.3570,
                'lat'            => -7.7345,
                'catatan'        => 'Catatan Rumah Tangga 7',
            ],
            [
                'kode_ruta'       => '444A008',
                'no_segmen'      => 2,
                'no_bg_fisik'    => 8,
                'no_bg_sensus'   => 8,
                'no_urut_rt'     => 8,
                'nama_krt'       => 'Rudi Santoso',
                'alamat'         => 'Jalan Malioboro, Yogyakarta',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 2,
                'no_urut_rt_egb' => 8,
                'long'           => 110.3630,
                'lat'            => -7.7820,
                'catatan'        => 'Catatan Rumah Tangga 8',
            ],
            [
                'kode_ruta'       => '444A009',
                'no_segmen'      => 2,
                'no_bg_fisik'    => 9,
                'no_bg_sensus'   => 9,
                'no_urut_rt'     => 9,
                'nama_krt'       => 'Diah Ratnasari',
                'alamat'         => 'Pakis, Sleman, DIY',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 3,
                'no_urut_rt_egb' => 9,
                'long'           => 110.4080,
                'lat'            => -7.7450,
                'catatan'        => 'Catatan Rumah Tangga 9',
            ],
            [
                'kode_ruta'       => '444A010',
                'no_segmen'      => 2,
                'no_bg_fisik'    => 10,
                'no_bg_sensus'   => 10,
                'no_urut_rt'     => 10,
                'nama_krt'       => 'Budi Santoso',
                'alamat'         => 'Malioboro, Yogyakarta',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '0',
                'jml_genz'       => null,
                'no_urut_rt_egb' => null,
                'long'           => 110.3634,
                'lat'            => -7.7825,
                'catatan'        => 'Catatan Rumah Tangga 10',
            ],
            [
                'kode_ruta'       => '444A011',
                'no_segmen'      => 3,
                'no_bg_fisik'    => 11,
                'no_bg_sensus'   => 11,
                'no_urut_rt'     => 11,
                'nama_krt'       => 'Ika Susanti',
                'alamat'         => 'Prambanan, Sleman, DIY',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 2,
                'no_urut_rt_egb' => 10,
                'long'           => 110.4932,
                'lat'            => -7.7523,
                'catatan'        => 'Catatan Rumah Tangga 11',
            ],
            [
                'kode_ruta'       => '444A012',
                'no_segmen'      => 3,
                'no_bg_fisik'    => 12,
                'no_bg_sensus'   => 12,
                'no_urut_rt'     => 12,
                'nama_krt'       => 'Surya Pratama',
                'alamat'         => 'Kalibawang, Kulon Progo',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 4,
                'no_urut_rt_egb' => 11,
                'long'           => 110.1031,
                'lat'            => -7.8475,
                'catatan'        => 'Catatan Rumah Tangga 12',
            ],
            [
                'kode_ruta'       => '444A013',
                'no_segmen'      => 3,
                'no_bg_fisik'    => 13,
                'no_bg_sensus'   => 13,
                'no_urut_rt'     => 13,
                'nama_krt'       => 'Rina Indah',
                'alamat'         => 'Sentolo, Kulon Progo',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 3,
                'no_urut_rt_egb' => 12,
                'long'           => 110.1995,
                'lat'            => -7.8236,
                'catatan'        => 'Catatan Rumah Tangga 13',
            ],
            [
                'kode_ruta'       => '444A014',
                'no_segmen'      => 3,
                'no_bg_fisik'    => 14,
                'no_bg_sensus'   => 14,
                'no_urut_rt'     => 14,
                'nama_krt'       => 'Faisal Rahman',
                'alamat'         => 'Bokoharjo, Sleman, DIY',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 2,
                'no_urut_rt_egb' => 13,
                'long'           => 110.3779,
                'lat'            => -7.7892,
                'catatan'        => 'Catatan Rumah Tangga 14',
            ],
            [
                'kode_ruta'       => '444A015',
                'no_segmen'      => 3,
                'no_bg_fisik'    => 15,
                'no_bg_sensus'   => 15,
                'no_urut_rt'     => 15,
                'nama_krt'       => 'Ani Cahyani',
                'alamat'         => 'Wonosari, Gunungkidul',
                'no_bs'          => '444A',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 3,
                'no_urut_rt_egb' => 14,
                'long'           => 110.6229,
                'lat'            => -7.9823,
                'catatan'        => 'Catatan Rumah Tangga 15',
            ],
            [
                'kode_ruta'       => '444B001',
                'no_segmen'      => 4,
                'no_bg_fisik'    => 16,
                'no_bg_sensus'   => 16,
                'no_urut_rt'     => 16,
                'nama_krt'       => 'Surya Wijaya',
                'alamat'         => 'Ngestiharjo, Kasihan, Bantul',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 3,
                'no_urut_rt_egb' => 15,
                'long'           => 110.3750,
                'lat'            => -7.8745,
                'catatan'        => 'Catatan Rumah Tangga 16',
            ],
            [
                'kode_ruta'       => '444B002',
                'no_segmen'      => 4,
                'no_bg_fisik'    => 17,
                'no_bg_sensus'   => 17,
                'no_urut_rt'     => 17,
                'nama_krt'       => 'Yulia Damayanti',
                'alamat'         => 'Depok, Sleman, DIY',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 2,
                'no_urut_rt_egb' => 16,
                'long'           => 110.4090,
                'lat'            => -7.7601,
                'catatan'        => 'Catatan Rumah Tangga 17',
            ],
            [
                'kode_ruta'       => '444B003',
                'no_segmen'      => 4,
                'no_bg_fisik'    => 18,
                'no_bg_sensus'   => 18,
                'no_urut_rt'     => 18,
                'nama_krt'       => 'Dwi Prasetyo',
                'alamat'         => 'Kalasan, Sleman, DIY',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '0',
                'jml_genz'       => null,
                'no_urut_rt_egb' => null,
                'long'           => 110.4275,
                'lat'            => -7.8023,
                'catatan'        => 'Catatan Rumah Tangga 18',
            ],
            [
                'kode_ruta'       => '444B004',
                'no_segmen'      => 4,
                'no_bg_fisik'    => 19,
                'no_bg_sensus'   => 19,
                'no_urut_rt'     => 19,
                'nama_krt'       => 'Lia Wulandari',
                'alamat'         => 'Piyungan, Bantul, DIY',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 3,
                'no_urut_rt_egb' => 17,
                'long'           => 110.3401,
                'lat'            => -7.8580,
                'catatan'        => 'Catatan Rumah Tangga 19',
            ],
            [
                'kode_ruta'       => '444B005',
                'no_segmen'      => 4,
                'no_bg_fisik'    => 20,
                'no_bg_sensus'   => 20,
                'no_urut_rt'     => 20,
                'nama_krt'       => 'Aditya Nugroho',
                'alamat'         => 'Jalan Kaliurang, Sleman, DIY',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 2,
                'no_urut_rt_egb' => 18,
                'long'           => 110.4112,
                'lat'            => -7.6950,
                'catatan'        => 'Catatan Rumah Tangga 20',
            ],
            [
                'kode_ruta'       => '444B006',
                'no_segmen'      => 5,
                'no_bg_fisik'    => 21,
                'no_bg_sensus'   => 21,
                'no_urut_rt'     => 21,
                'nama_krt'       => 'Fajar Budiman',
                'alamat'         => 'Condongcatur, Depok, Sleman',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 3,
                'no_urut_rt_egb' => 19,
                'long'           => 110.3762,
                'lat'            => -7.7678,
                'catatan'        => 'Catatan Rumah Tangga 21',
            ],
            [
                'kode_ruta'       => '444B007',
                'no_segmen'      => 5,
                'no_bg_fisik'    => 22,
                'no_bg_sensus'   => 22,
                'no_urut_rt'     => 22,
                'nama_krt'       => 'Rini Cahyani',
                'alamat'         => 'Berbah, Sleman, DIY',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 2,
                'no_urut_rt_egb' => 20,
                'long'           => 110.4040,
                'lat'            => -7.7435,
                'catatan'        => 'Catatan Rumah Tangga 22',
            ],
            [
                'kode_ruta'       => '444B008',
                'no_segmen'      => 5,
                'no_bg_fisik'    => 23,
                'no_bg_sensus'   => 23,
                'no_urut_rt'     => 23,
                'nama_krt'       => 'Yanto Prasetyo',
                'alamat'         => 'Kretek, Bantul, DIY',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 4,
                'no_urut_rt_egb' => 21,
                'long'           => 110.3385,
                'lat'            => -7.9115,
                'catatan'        => 'Catatan Rumah Tangga 23',
            ],
            [
                'kode_ruta'       => '444B009',
                'no_segmen'      => 5,
                'no_bg_fisik'    => 24,
                'no_bg_sensus'   => 24,
                'no_urut_rt'     => 24,
                'nama_krt'       => 'Dina Wahyuni',
                'alamat'         => 'Nglipar, Gunungkidul',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 3,
                'no_urut_rt_egb' => 22,
                'long'           => 110.5483,
                'lat'            => -7.9523,
                'catatan'        => 'Catatan Rumah Tangga 24',
            ],
            [
                'kode_ruta'       => '444B010',
                'no_segmen'      => 5,
                'no_bg_fisik'    => 25,
                'no_bg_sensus'   => 25,
                'no_urut_rt'     => 25,
                'nama_krt'       => 'Iqbal Hakim',
                'alamat'         => 'Banguntapan, Bantul, DIY',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 2,
                'no_urut_rt_egb' => 23,
                'long'           => 110.3482,
                'lat'            => -7.8301,
                'catatan'        => 'Catatan Rumah Tangga 25',
            ],
            [
                'kode_ruta'       => '444B011',
                'no_segmen'      => 6,
                'no_bg_fisik'    => 26,
                'no_bg_sensus'   => 26,
                'no_urut_rt'     => 26,
                'nama_krt'       => 'Linda Wijaya',
                'alamat'         => 'Bantul, Bantul, DIY',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 1,
                'no_urut_rt_egb' => 24,
                'long'           => 110.3290,
                'lat'            => -7.8967,
                'catatan'        => 'Catatan Rumah Tangga 26',
            ],
            [
                'kode_ruta'       => '444B012',
                'no_segmen'      => 6,
                'no_bg_fisik'    => 27,
                'no_bg_sensus'   => 27,
                'no_urut_rt'     => 27,
                'nama_krt'       => 'Rizki Pratiwi',
                'alamat'         => 'Srandakan, Bantul, DIY',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 3,
                'no_urut_rt_egb' => 25,
                'long'           => 110.4018,
                'lat'            => -7.9263,
                'catatan'        => 'Catatan Rumah Tangga 27',
            ],
            [
                'kode_ruta'       => '444B013',
                'no_segmen'      => 6,
                'no_bg_fisik'    => 28,
                'no_bg_sensus'   => 28,
                'no_urut_rt'     => 28,
                'nama_krt'       => 'Eko Setiawan',
                'alamat'         => 'Imogiri, Bantul, DIY',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 4,
                'no_urut_rt_egb' => 26,
                'long'           => 110.3667,
                'lat'            => -7.9420,
                'catatan'        => 'Catatan Rumah Tangga 28',
            ],
            [
                'kode_ruta'       => '444B014',
                'no_segmen'      => 6,
                'no_bg_fisik'    => 29,
                'no_bg_sensus'   => 29,
                'no_urut_rt'     => 29,
                'nama_krt'       => 'Fajar Hakim',
                'alamat'         => 'Anggrek, Bantul, DIY',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 3,
                'no_urut_rt_egb' => 27,
                'long'           => 110.4018,
                'lat'            => -7.9263,
                'catatan'        => 'Catatan Rumah Tangga 29',
            ],
            [
                'kode_ruta'       => '444B015',
                'no_segmen'      => 6,
                'no_bg_fisik'    => 30,
                'no_bg_sensus'   => 30,
                'no_urut_rt'     => 30,
                'nama_krt'       => 'Reza Surya',
                'alamat'         => 'Nglipar, Gunungkidul',
                'no_bs'          => '444B',
                'is_genz_ortu'   => '1',
                'jml_genz'       => 4,
                'no_urut_rt_egb' => 28,
                'long'           => 110.3667,
                'lat'            => -7.9420,
                'catatan'        => 'Catatan Rumah Tangga 30',
            ]
        ];
        $this->db->table('rumahtangga')->insertBatch($data);
    }
}
